### ISSUE TITLE
Sequelizeを利用したデータベースを構築する

### ISSUE THREAD

**Issue by Raystar247** [Raystar247/QCmX#8]
## 概要
Backend側でSequelizeを利用したデータベースを構築する

## 目的
将来的に大規模なデータを処理していくため

## 内容
データベースの環境構築と基盤の実装を行う
- Sequelizeパッケージのインストール・設定
- データベースの作成などデータ操作のための基盤構築
  - データベースはSQLite3を使用する
- ユーザー登録にかかるテーブル・処理の実装
  - Userクラス

## 本issueのゴール
ブラウザから登録したデータがBackend側のデーターベースに反映される状態

### 本issueで取り扱わないこと
- 複数のテーブルの追加・管理

## 本issueのタスク
- [x] Backend側でフォルダ構成を再実装する
- [x] Sequelizeのインストール
- [x] Sequelizeを使用してデータベースを作成・基盤を構築する
- [x] ユーザー登録情報をデータベースにcreateする

**Comment by Raystar247** [comment]
# エラー発生
**SQLITE_ERROR: no such table: Users**

## エラー概要
### 発生箇所
`/user/all`エンドポイントに対するgetリクエスト

### 概要
`User.init`関数でテーブル作成している状態で, `no such table: Users`エラーが出現し, 
その後, セッションが自動で終了した。

## Error Trace
```
Executing (default): SELECT `id`, `username`, `email`, `password`, `createdAt`, `updatedAt` FROM `Users` AS `User`;
/Users/ren_sakai/Work/GitHub/QCmX/backend/node_modules/sequelize/src/dialects/sqlite/query.js:236
      const errForStack = new Error();
                          ^
Error
    at Database.<anonymous> (/Users/ren_sakai/Work/GitHub/QCmX/backend/node_modules/sequelize/src/dialects/sqlite/query.js:236:27)
    at /Users/ren_sakai/Work/GitHub/QCmX/backend/node_modules/sequelize/src/dialects/sqlite/query.js:234:50
    at new Promise (<anonymous>)
    at Query.run (/Users/ren_sakai/Work/GitHub/QCmX/backend/node_modules/sequelize/src/dialects/sqlite/query.js:234:12)
    at /Users/ren_sakai/Work/GitHub/QCmX/backend/node_modules/sequelize/src/sequelize.js:650:28
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SQLiteQueryInterface.select (/Users/ren_sakai/Work/GitHub/QCmX/backend/node_modules/sequelize/src/dialects/abstract/query-interface.js:1001:12)
    at async Function.findAll (/Users/ren_sakai/Work/GitHub/QCmX/backend/node_modules/sequelize/src/model.js:1824:21) {
  name: 'SequelizeDatabaseError',
  parent: [Error: SQLITE_ERROR: no such table: Users] {
    errno: 1,
    code: 'SQLITE_ERROR',
    sql: 'SELECT `id`, `username`, `email`, `password`, `createdAt`, `updatedAt` FROM `Users` AS `User`;'
  },
  original: [Error: SQLITE_ERROR: no such table: Users] {
    errno: 1,
    code: 'SQLITE_ERROR',
    sql: 'SELECT `id`, `username`, `email`, `password`, `createdAt`, `updatedAt` FROM `Users` AS `User`;'
  },
  sql: 'SELECT `id`, `username`, `email`, `password`, `createdAt`, `updatedAt` FROM `Users` AS `User`;',
  parameters: {}
}
```

## エラー対応履歴
- User.initの後にconsoleログを仕込んで, ログが表示されるかの確認
  - 仮説: User.initの処理が行われていない可能性がある
  - 結果: getリクエストを受け付ける前にログは表示された
- getリクエスト時にUsersテーブルがあるかの確認
  - 目的: テーブル作成の挙動を確認する
  - 結果: 
    - レコードがない時には`[ [ { 'COUNT(*)': 0 } ], Statement {} ]`
    - postリクエストを受け付けた後には`[ [ { 'COUNT(*)': 1 } ], Statement {} ]`

## 原因
`/user/all`エンドポイントに対するget処理の際にテーブルが作成されていなかった
- createした際には, create処理の段階でテーブルが作成されてるため問題にならなかった

## 解決策
sync関数をgetの時にも呼び出すようにコードを修正した。

https://github.com/Raystar247/QCmX/blob/931c5631d27cefc74b2f88ec091d54cf8319f1d3/backend/models/User.ts#L24-L25
